### PR TITLE
 Don't duplicate simple primary keys in the link column

### PR DESCRIPTION
**Pull request by russss**
When there's a simple (single-column) primary key, it looks weird to duplicate it in the link column.

This change removes the second PK column and treats the link column as if it were the PK column from a header/sorting perspective. 

This might make it a bit more difficult to tell what the link for the row is, I'm not sure yet. I feel like the alternative is to change the link column to just have the text "view" or something, instead of repeating the PK. (I doubt it makes much more sense with compound PKs.)

Bonus change in this PR: fix urlencoding of links in the displayed HTML.

Before:
image

After:
image

### CODE REVIEW

**Comment by russss** [comment]
I suspected this would cause some test failures, but I'll wait for opinions before attempting to fix them.

**Comment by simonw** [comment]
I think this is a good improvement. If you fix the tests I'll merge it.

**Comment by russss** [comment]
Tests now fixed, honest. The failing test on Travis looks like an intermittent sqlite failure which should resolve itself on a retry...

**Comment by russss** [comment]
I've added another commit which puts classes a class on each `<td>` by default with its column name, and I've also made the PK column bold.

Unfortunately the tests are still failing on 3.6, which is weird. I can't reproduce locally...

**Comment by simonw** [comment]
I managed to get a better error message out of that text. The server is returning this (but only on Python 3.6, not on Python 3.5 - and only in Travis, not in my local environment):

```{'error': 'interrupted', 'ok': False, 'status': 400, 'title': 'Invalid SQL'}```

https://travis-ci.org/simonw/datasette/jobs/367929134

**Comment by simonw** [comment]
OK, aaf59db570ab7688af72c08bb5bc1edc145e3e07 should mean that the tests pass when I merge that.

**Pull request merged**
