### PR TITLE
Refactor facets to a class and new plugin, refs #427

### PR DESCRIPTION
**Pull request by simonw**
WIP for #427

### CODE REVIEW

**Comment by simonw** [comment]
This has a bug which isn't being caught by the unit tests (yet) - facet suggestion suggests facets that have already been enabled:

fixtures__facetable__15_rows

There is also a test failure due to missing plugin hook documentation.

**Comment by simonw** [comment]
It would be nice to decouple the `request` object from the `Facet` class. The request is needed for two things at the moment:

* To decide if a specific facet bucket has been selected or not
* To construct the `toggle_url` for turning the selection on or off

Can I pull those needs out of the Facet class somehow?

**Comment by russss** [comment]
> Can I pull those needs out of the Facet class somehow?

I was thinking that it might be handy for datasette to have a request object which wraps the Sanic Request. This could include the datasette-specific querystring decoding and the `special_args` parsing from TableView.data.

This would mean that we could expose the request object to plugin hooks without coupling them to Sanic.

**Comment by simonw** [comment]
Abandoning this in favour of #445 - which contains the code from this branch but updated to incorporate recent changes in master.

**Pull request closed without merging**
