### PR TITLE
Don't auto-format SQL on page load

### PR DESCRIPTION
**Pull request by simonw**
Refs #600

### CODE REVIEW

**Comment by simonw** [comment]
@rixx does this look like the right way to do #600 to you?

**Comment by rixx** [comment]
That looks right, and I completely agree with the intent.

**Comment by rixx** [comment]
The only negative impact that comes to mind is that now you have no way to get the read-only query to be formatted nicely, I think, so maybe a second PR adding the formatting functionality even to the read-only page would be good?

**Comment by simonw** [comment]
That's a good idea. It could even be smart about it and only show the "Format SQL" button on that page of the output of the function would differ from what's there already.

**Comment by rixx** [comment]
Submitted in #602!

**Pull request merged**
